version: 2
updates:
  - package-ecosystem: maven
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 0

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 0

  - package-ecosystem: cargo
    directory: /jg-launcher
    schedule:
      interval: weekly
    open-pull-requests-limit: 0
